#!/bin/sh

#PBS -N mrna_pipeline
#PBS -l nodes=1:ppn=30
#PBS -o /path for output/job.$PBS_JOBID.out
#PBS -e /path for error/job.$PBS_JOBID.err

set -e

# Parameters
Proc=30
Software_Directory="/path/Software"
Out_Directory="/path/Aradu"
Scratch_Directory="/path/Aradu"
Min_length=200

export FEELNCPATH=/path/FEELnc/bin/
export PERL5LIB=$PERL5LIB:/path/FEELnc/lib/


# Peanut
Rna_seq_folder="/path/RNA_Seq"
Genome="/path/GCF_000817695.2_Aradu1.1_genomic.fna"
Index="/path/GCF_000817695.2_Aradu1.1_genomic"
mRNA="/path/Aradu_mRNA.gtf"
Annotation="/path/GCF_000817695.2_Aradu1.1_genomic.gtf"

# Automatically gather SRA IDs from the folder
SRAids=()
for file in $Rna_seq_folder/*.fastq; do
    filename=$(basename "$file")
    sraid="${filename%%.*}"  # Extract the part before the first dot (.)
    SRAids+=("$sraid")
    echo "$sraid"
done

# Tool Paths
Hisat_Path="$Software_Directory/hisat-3n"
Bwa_Path="$Software_Directory/bwa"
Samtool_Path="$Software_Directory/samtool/samtools-1.3.1/samtools"
Bedtool_Path="$Software_Directory/bedtools2/bin"
Stringtie_Path="$Software_Directory/stringtie-2.2.1/stringtie"
GFFread_Path="$Software_Directory/gffread"
GFFCompare_Path="$Software_Directory/gffcompare"
Python_Path="/usr/local/bin/python3"
FEELnc_Path="$Software_Directory/FEELnc/scripts"

# Index the reference genome
index_genome() {
    if [ ! -f "${Index}.1.ht2" ]; then
        $Hisat_Path/hisat2-build -p $Proc $Genome $Index
    else
        echo "Index files already exist. Skipping hisat2-build."
    fi
}

# Align RNA-seq reads
align_reads() {
    local sraid=$1
    $Hisat_Path/hisat2 --new-summary --rna-strandness RF -p $Proc \
      -x $Index \
      -U $Rna_seq_folder/$sraid.clean.fastq \
      -S $Scratch_Directory/$sraid.sam
}

# Sort and compress alignments
sort_alignments() {
    local sraid=$1
    $Samtool_Path sort -o $Scratch_Directory/$sraid.bam $Scratch_Directory/$sraid.sam
}

# Assemble transcripts
assemble_transcripts() {
    local sraid=$1
    $Stringtie_Path -p $Proc --rf -G ${Index}.gtf -o $Scratch_Directory/$sraid.transcripts.gtf $Scratch_Directory/$sraid.bam
#   $Stringtie_Path -e -B -G ${Index}.gtf -o $Scratch_Directory/$sraid.transcripts.gtf $Scratch_Directory/$sraid.bam
    $GFFread_Path/gffread -w $Scratch_Directory/$sraid.transcripts.fasta -g $Genome $Scratch_Directory/$sraid.transcripts.gtf
    grep '>' $Scratch_Directory/$sraid.transcripts.fasta | awk '{print $1}' | sed 's/>//g' | sort -u > $Scratch_Directory/$sraid.transcripts.txt
}

# Merge transcripts
Merge_transcripts() {
    stringtie --merge -o candidate_transcript.gtf -G genome.gtf SRR*.gtf
    gffread -w candidate_transcript.fasta -g genome.fasta candidate_transcript.gtf
    grep '>' candidate_transcript.fasta | awk '{print $1}' | sed 's/>//g' | sort -u > candidate_transcript.txt
}

# Filter transcripts by length
filter_transcripts() {
    local sraid=$1
    awk -v min_length="$Min_length" '($5-$4) >= min_length { print $0 }' $Scratch_Directory/$sraid.transcripts.gtf > $Scratch_Directory/$sraid.long_transcripts.gtf
}

# Remove overlaps with known mRNAs
filter_long_transcript() {
    local sraid=$1
    $FEELnc_Path/FEELnc_filter.pl -i $Scratch_Directory/$sraid.long_transcripts.gtf -a $Scratch_Directory/Aradu_mRNA.gtf > $Scratch_Directory/$sraid.candidate_long_transcripts.gtf

    echo "$sraid: FEELnc filtering done"

    cut -d ";" -f 2 $Scratch_Directory/$sraid.candidate_long_transcripts.gtf | sed 's/ transcript_id //g' | sed 's/"//g' | sort -u > $Scratch_Directory/$sraid.long_transcripts.txt
}

# Using LncFinder-plant
LncFinder() {
    library(seqinr)
    library(LncFinder)
    
    Scratch <- "/path/Aradu"
    lnc_fasta <- file.path(Scratch, "Aradu_ncRNA_sequences.fasta")
    mrna_fasta <- file.path(Scratch, "Aradu_cds_sequences.fasta")
    
    frequency <- file.path(Scratch, "Aradu_frequencies.rda")
    plant_model <- file.path(Scratch, "Aradu_model.rda")
    
    mRNA <- seqinr::read.fasta(file = mrna_fasta)
    
    lncRNA <- seqinr::read.fasta(file = lnc_fasta)
    
    #generate the feature file
    #frequencies <- make_frequencies(cds.seq = mRNA, lncRNA.seq = lncRNA, SS.features = FALSE, cds.format = "DNA", lnc.format = "DNA", check.cds = TRUE, ignore.illegal = TRUE)
    
    # Make own model
    #Aradu_model <- build_model(lncRNA.seq = lncRNA, mRNA.seq = mRNA, frequencies, SS.features = FALSE, lncRNA.format = "DNA",mRNA.format = "DNA", parallel.cores = -1, folds.num = 10, seed = 1, gamma.range = (2^seq(-5, 0, 1)), cost.range = c(1, 4, 8, 16, 24, 32))
    
    # Save the model to a .rda file
    #save(Aradu_model, file = "$Scratch/Aradu_model.rda")
    
    
    #loading the model
    #plant = readRDS
    load(plant_model)
    load(frequency)
    ls()
    Seqs <- seqinr::read.fasta(file = candidate_transcript.fasta)
    Plant_results <- LncFinder::lnc_finder(Seqs, SS.features = FALSE, format = "DNA", frequencies.file = frequencies, svm.model = Aradu_model, parallel.cores = 2)
    write.table(Plant_results, file = "LncFinder_result.txt", sep ="\t",row.names =TRUE, col.names =TRUE,quote =FALSE)
}


# Using CPAT
CPAT() {
    lnc_fasta <- file.path(Scratch, "Aradu_ncRNA_sequences.fasta")
    mrna_fasta <- file.path(Scratch, "Aradu_cds_sequences.fasta")

    make_hexamer_tab -c mrna_fasta -n lnc_fasta > Aradu_Plant_Hexamer.tsv
    make_logitModel -x Aradu_Plant_Hexamer.tsv -c mrna_fasta -n lnc_fasta -o Aradu_Plant.logit.RData

    cpat -x $Scratch_Directory/Aradu_Plant_Hexamer.tsv -d $Scratch_Directory/Aradu_Plant.logit.RData.logit.RData -g $Scratch_Directory/candidate.transcripts.fasta --min-orf=120 -o $Scratch_Directory/CPAT_plant.output
}

# Using Uniprot
UniProt() {
    $Software_Directory/diamond makedb --in uniprot_sprot.fasta -d uniprot_out
    $Software_Directory/diamond blastx -d uniprot_out -q $Scratch_Directory/candidate_transcripts.fasta -o $Scratch_Directory/uniprotoutput.txt
}

# Using FEELnc
FEELnc() {
    $GFFCompare_Path -r $Annotation -o $WD/MERGED_gffcompare_gtfoutput.gtf $SD/candidate_transcript.gtf
        
    $FEELnc_Path/FEELnc_filter.pl  \
        -p 12 -i $MERGED_gffcompare_gtfoutput.gtf.annotated.gtf  \
        -a $Annotation -b transcript_biotype=protein_coding \
        --monoex=-1  \
        -o $WD/FEELnc_filtered_trimmed_MERGED_gffcompare.out  \
        > $WD/Candidatelnc_FEELnc_Filtered.gtf
        
    $FEELnc_Path/FEELnc_codpot.pl \
        -p 12 \
        -i $WD/Candidatelnc_FEELnc_Filtered.gtf \
        -a $Annotation \
        -g $Genome  \
        -b transcript_biotype=protein_coding \
        --outdir $WD/Coding_Potential \
        --outname=Aradu_Feelnc \
        --mode=shuffle

    $FEELnc_Path/FEELnc_classifier.pl \
        --biotype -i \
        $WD/Coding_Potential/Aradu_Feelnc.lncRNA.gtf \
        -a $Annotation \
        > $WD/FEELnc_lncRNA_classes.txt
    }

# Combine CPC2 + LncFinder + CPAT + Uniprot + FEELnc
Result_combine() {
    Intersect all lncRNAs from 
}



# Main Pipeline Execution
index_genome

echo "Processing Stage 1"

for sraid in "${SRAids[@]}"; do
    echo "Processing sample: $sraid"
    align_reads $sraid
    sort_alignments $sraid
    assemble_transcripts $sraid
done

echo "Processing Stage 2"

Merge_transcripts
filter_transcripts 
filter_long_transcript 
LncFinder $sraid
CPAT $sraid
UniProt
FEELnc 
Result_combine



echo "Pipeline completed successfully."
